### ISSUE TITLE
Add support for Svelte 5 generics

### ISSUE THREAD

**Issue by marekdedic** [sveltejs/svelte-eslint-parser#583] opened 2024-11-08 13:44 UTC
### Description

Hi,
generics are now [officially](https://svelte.dev/docs/svelte/typescript#Generic-$props) part of Svelte 5. However, it seems to me that this parsers doesn't support them:

```svelte
<script generics="KeyType extends number | string, ValueType" lang="ts">
  import type { Snippet } from "svelte";

  interface Props {
    children?: Snippet<[KeyType, ValueType]>;
    options: Array<[KeyType, ValueType]>;
    selected: Array<KeyType>;
  }

  let { children, options, selected = $bindable() }: Props = $props();

  selected;
</script>

{#each options as [id, value] (id)}
  <label>
    <input type="checkbox" value={id} bind:group={selected} />
    <span></span>
    {@render children?.(id, value)}
  </label>
{/each}
```

Gives `'ValueType' is not defined` and similar

I tried to create a [repro](https://eslint-online-playground.netlify.app/#eNq1VU1v2zAM/SuEtkNSuPbdS7oO+7gMwwps2KXuQbEZV6kiG5JcNPD830dZkuO0RTds2KkR+Ug+PpJuz4wusy+H982+bRQqm5p7lBZZzlam1KK1UKNCLUqzLthnPHw/tAj4YFFVBlS336CGn2CsFqpO4AeXHTpIwUByVVOMNQW7KBSAoAragnUJevimRNuihQG2utlDwXzdgr0p1IhWFvWWlwhXumkN9M4IUN4KWWlUb/OYYXUdWM2q31xQFgdvWisaZXJ4pzU/vAg1KLG0WEVsgHr34ElJItxPHJKYPpmCYQ2vN0JVfCNxsYQhD+zJ3Lofi2VoLwbQc5V5oUmkQvWvkJe3MTFwA9eiSuDe0b2BhaiWRAVgJfkG5SgrPYRqOy8s6V3eYnm3aR5oAmPUuhfVAI5UXuuma9d9rD1AFjOYlqsLIuL+eFN/SR1WNNxJ8ZSqByaBRBZZ9JljPbCEoZE0ubRs1FbU6c7QHoW570yc9KUHZTvaDOo/+P38r2RXCxWRHnjejsbz2YacxnBtiOjJHp3H0NE3j7HGuyLeyeYHEGJGMD6M4Aq3vJPHoNDYwrW/M+FlUo1ls987varEudI0fRTxLGbecsRdF2wruc1m8ILdjBHhBLZCIm00Ac/OsrOQpGAJ9XJ8+QjaWDrCjtf4NR5CSALglclPNAxB0fk06Bg2MwHJk7u5PpEyi/JPiemUZr/pO6L5J+rno/ugGF+MGnvSxjFs3Dz/eEkP0v9UktHw31WZpu4Nf83encYJe2f4J/ZT5eUbOtOWl3eUgdI2ik50TOBPoWBulPum6qRbKu+o8P4Dtm4ZVSmQqEw1T6/ZhdLyoqEjCnXjEb/ofHzhz0L/wPn46p+FHrf0t4DpizDHhf8HAxt+AQnmbM4=), but the playground is stuck at "Starting WebContainer"...

**Comment by ota-meshi** [comment] 2024-11-08 13:57
I wasn't aware that `generics` were now an official feature 👀 
For now it works fine if you enable it in the parser configuration.

See https://github.com/sveltejs/svelte-eslint-parser?tab=readme-ov-file#parseroptionssveltefeatures

```js
      parserOptions: {
        // ...
        svelteFeatures: {
          experimentalGenerics: true,
        }
      },
```

**Comment by ota-meshi** [comment] 2024-11-08 14:05
> I tried to create a [repro](https://eslint-online-playground.netlify.app/#eNq1VU1v2zAM/SuEtkNSuPbdS7oO+7gMwwps2KXuQbEZV6kiG5JcNPD830dZkuO0RTds2KkR+Ug+PpJuz4wusy+H982+bRQqm5p7lBZZzlam1KK1UKNCLUqzLthnPHw/tAj4YFFVBlS336CGn2CsFqpO4AeXHTpIwUByVVOMNQW7KBSAoAragnUJevimRNuihQG2utlDwXzdgr0p1IhWFvWWlwhXumkN9M4IUN4KWWlUb/OYYXUdWM2q31xQFgdvWisaZXJ4pzU/vAg1KLG0WEVsgHr34ElJItxPHJKYPpmCYQ2vN0JVfCNxsYQhD+zJ3Lofi2VoLwbQc5V5oUmkQvWvkJe3MTFwA9eiSuDe0b2BhaiWRAVgJfkG5SgrPYRqOy8s6V3eYnm3aR5oAmPUuhfVAI5UXuuma9d9rD1AFjOYlqsLIuL+eFN/SR1WNNxJ8ZSqByaBRBZZ9JljPbCEoZE0ubRs1FbU6c7QHoW570yc9KUHZTvaDOo/+P38r2RXCxWRHnjejsbz2YacxnBtiOjJHp3H0NE3j7HGuyLeyeYHEGJGMD6M4Aq3vJPHoNDYwrW/M+FlUo1ls987varEudI0fRTxLGbecsRdF2wruc1m8ILdjBHhBLZCIm00Ac/OsrOQpGAJ9XJ8+QjaWDrCjtf4NR5CSALglclPNAxB0fk06Bg2MwHJk7u5PpEyi/JPiemUZr/pO6L5J+rno/ugGF+MGnvSxjFs3Dz/eEkP0v9UktHw31WZpu4Nf83encYJe2f4J/ZT5eUbOtOWl3eUgdI2ik50TOBPoWBulPum6qRbKu+o8P4Dtm4ZVSmQqEw1T6/ZhdLyoqEjCnXjEb/ofHzhz0L/wPn46p+FHrf0t4DpizDHhf8HAxt+AQnmbM4=), but the playground is stuck at "Starting WebContainer"...

That link works fine on my local computer, I don't know what the problem is...

**Comment by marekdedic** [comment] 2024-11-08 14:26
Great, I enabled the config and it works, thanks! They're official, so maybe it's time to stabilize them here as well :)

**Comment by ota-meshi** [comment] 2024-11-16 01:09
Well, the RFC hasn't been merged yet, but it's in the official documentation so we can probably consider it an official feature.

**Closed** 2024-11-27 07:31 UTC
Labels: enhancement
